### ISSUE TITLE
Markdown - Unable To Display User's Avatar In Markdown

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/mattermost-server#10364]
#### Summary
When I try to display a user's avatar as a markdown image, it doesn't work. I'm able to access the image if I directly open the URL in the browser.

#### Steps to reproduce
1. Generate a user's avatar URL following this scheme - `/api/v4/users/<user_id>/image?_=1551141926912`.
1. Try sending this image URL as an inline markdown image - `![](<generated-user-avatar-url>)`.

#### Expected behavior
The user's avatar is successfully displayed as an inline image.

#### Observed behavior (that appears unintentional) 
The user's avatar is not displayed at all.

#### Possible fixes
I debugged a bit into the `/api/v4/image` API. For the image URLs I generate, the API sends this response - `forbidden content-type: "application/json"`.

**Comment by harshilsharma63** [comment]
This seems to be related to #10299 as I'm able to see images if I turn off image proxy.

**Comment by amyblais** [comment]
Hi @harshilsharma63, can you help take a look at the comments posted by ``hmhealey`` on the issue that you referenced and see if they help with this issue?

**Comment by amyblais** [comment]
Hi @harshilsharma63,

We just released v5.8.1 dot release and v5.9.0 release which include fixes around image proxy. Can you help upgrade to either version and see if that helps with your issue?

More details in important upgrade notes: https://docs.mattermost.com/administration/important-upgrade-notes.html.

**Comment by harshilsharma63** [comment]
@amyblais I'm running from Mattermost locally directly off `release-5.9` branch and this still occurs for me.

**Comment by DHaussermann** [comment]
Hi @harshilsharma63 I'm not seeing this issue. I just want to make sure I understand the problem.

- Does the profile image fail to render anywhere else and in the app and does it display as expected when you hit it in a new browser tab?
- Are you seeing this issue with any other images when you put them in the in-line markdown in this way?

**Comment by amyblais** [comment]
Closing this for now as there hasn't been updates on this for a while. Please re-open this issue if the problem persists,
