### ISSUE TITLE
Latest version uprade 4.2.3 no longer tile flashes when new post is received. All settings are correct inclusive of Win. Please advise. Thanks. 

### ISSUE THREAD

**Issue by shanetrush** [mattermost/mattermost-server#12080]
#### Summary
Bug report in one concise sentence

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

#### Expected behavior
Describe your issue in detail

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
Hi @shanetrush, are you referring to the setting "Flash taskbar icon when a new message is received"? What Windows version are you on?

**Comment by shanetrush** [comment]
Absolutely correct. Win10 64-bit 1709 build. Thanks!

Shane Trush
SC, Denver Region

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18386.

**Comment by shanetrush** [comment]
Thanks Amy! Appreciate your help. I’ve uninstalled and reinstalled MM. I’ve disabled and re-enabled the notification settings in both MM and Win. Thanks in advance. My colleague says the same (enabled but no tile flash).

Shane Trush
SC, Denver Region

**Comment by resforn65** [comment]
Just wanted to share that we're also experiencing this. Tried all the same troubleshooting as well, and even killed the cache on the client _completely_.

**Comment by amyblais** [comment]
Closing as this is fixed for v4.3 desktop app version. v4.3 release is scheduled for October 16th, but any slight delays may be possible.

**Comment by shanetrush** [comment]
Awesome. Thanks Amy! We appreciate it. We use MM as our primary communication tool for our infrastructure team.

Thanks again!

Shane Trush
SC, Denver Region

**Comment by shanetrush** [comment]
Afternoon Amy,

So a couple of us upgraded to 4.3.1. We still get the dot on the MM system tray icon, we get the temp window flash, but still the tile won’t flash.

Win10 1709 (build 16299.1451).

All notification settings are turned on inside MM and Win. Tested with several users on multiple machines. Thanks in advance.

Shane Trush
SC, Denver Region

From: Trush, Shane
Sent: Thursday, September 26, 2019 11:35 AM
To: 'mattermost/mattermost-server' <reply@reply.github.com>; mattermost/mattermost-server <mattermost-server@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [EXTERNAL] Re: [mattermost/mattermost-server] Latest version upgrade 4.2.3 no longer tile flashes when new post is received. All settings are correct inclusive of Win. Please advise. Thanks. (#12080)

Awesome. Thanks Amy! We appreciate it. We use MM as our primary communication tool for our infrastructure team.

Thanks again!

Shane Trush
SC, Denver Region

**Comment by amyblais** [comment]
@shanetrush What Mattermost server version are you on?

**Comment by shanetrush** [comment]
Enterprise Edition Mattermost Version: 5.11.0

Shane Trush
SC, Denver Region

**Comment by amyblais** [comment]
@shanetrush I'm not able to reproduce this but I'm on v5.16 server version. I'm wondering if you're open to consider updating your server version to see if the issue gets fixed?

**Comment by shanetrush** [comment]
I’ll send a request up to see if they will upgrade. Thanks!

Shane Trush
SC, Denver Region
