### ISSUE TITLE
command line broken in Docker since the 5.11.1 -> 5.12.0 transition

### ISSUE THREAD

**Issue by prof-foster** [mattermost/mattermost-server#12327]
#### Summary
Running using docker-compose and trying to run the `mattermost` command line results in "Failed to ping DB retrying in 10 seconds"

#### Steps to reproduce

```
mkdir /tmp/mattermost
cd  /tmp/mattermost
git clone https://github.com/mattermost/mattermost-docker.git
cd /tmp/mattermost/mattermost-docker
git checkout tags/5.12.0
vi /tmp/mattermost/mattermost-docker/docker-compose.yml 
        - edition=team
        - PUID=1000
        - PGID=1000
docker-compose build --force-rm --pull 
docker-compose up -d
docker exec mattermostdocker_app_1 sh -c '/mattermost/bin/mattermost --help'
docker exec mattermostdocker_app_1 sh -c '/mattermost/bin/mattermost team create --name test --display_name "Test"'
docker exec mattermostdocker_app_1 sh -c '/mattermost/bin/mattermost team list'
```

#### Expected behavior
The team test will be listed.

#### Observed behavior (that appears unintentional) 
As per https://forum.mattermost.org/t/cannot-connect-to-the-postgresql-database-using-mattermost-cli/7809 "Failed to ping DB retrying in 10 seconds"

#### Possible fixes
```
git checkout tags/5.11.1
```

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-18794.

**Comment by cadavre** [comment]
I can confirm this behavior. FYI

```
docker exec -it 82ce7fde8ee4 env
PATH=/mattermost/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=82ce7fde8ee4
TERM=xterm
DB_HOST=postgres
DB_PORT_NUMBER=5432
MM_DBNAME=mattermost
MM_PASSWORD=mattermost
MM_USERNAME=mattermost
edition=team
MM_VERSION=5.15.0
HOME=/mattermost
```

`DB_HOST` exists and is resolved to database container IP.

The problem looks like Mattermost CLI is not respecting `$DB_HOST` and is stubbornly using `localhost` instead.

**Comment by santiago-espinosa** [comment]
Has this been fixed in the new release? 
I'm very hesitant of deploying 5.11.1 considering the large number of bug fixes since then.

**Comment by Zoddo** [comment]
@amyblais Hi, any news about this issue (it still exists in 5.16.0)? We are currently blocked from doing some tasks which can only be run from the cli.

Maybe there is a temporarily work-around? I tried to manually provide the config file path (`-c` option) or the `DB_HOST` env without success.

**Comment by amyblais** [comment]
Hey all, you can follow the progress of the fix here: https://github.com/mattermost/mattermost-docker/pull/421.

**Comment by amyblais** [comment]
Closing as the PR above was merged, please re-open this issue if the problem persists,
