### ISSUE TITLE
Upload of SAML Identity Provider Public Certificate fails

### ISSUE THREAD

**Issue by hajowieland** [mattermost/mattermost-server#14124]
#### Summary
Error when trying to upload the Identity Provider Public Certificate for SAML from an Auth0 application

#### Steps to reproduce
- Create Auth0 application
- Configure SAML in Mattermost
- Upload Identity Provider Certificate (Choose File > Upload)

#### Expected behavior
Uploading of IDP certificate

#### Observed behavior (that appears unintentional)
- Upload seems to work (no error in System Console)
- Filename in System console appears to be _saml-idp.crt_ (instead of mycert.pem which was uploaded)

**Log:**

`[mattermost-mattermost-enterprise-edition-7694d6cbdc-5zk2r mattermost-enterprise-edition] {"level":"error","ts":1584898281.9585395,"caller":"app/enterprise.go:154","msg":"An error occurred while configuring SAML Service Provider","error":"failed to load idp public certificate: failed to get config file saml-idp.crt: failed to scan data from row for saml-idp.crt: pq: syntax error at end of input","errorVerbose":"pq: syntax error at end of input\nfailed to scan data from row for saml-idp.crt\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).GetFile\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:278\ngithub.com/mattermost/mattermost-server/v5/app.(*App).GetConfigFile\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:359\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:273\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357\nfailed to get config file saml-idp.crt\ngithub.com/mattermost/mattermost-server/v5/app.(*App).GetConfigFile\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:361\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:273\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357\nfailed to load idp public certificate\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:275\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357"}
`

#### Possible fixes
--

**Comment by amyblais** [comment]
@hajowieland What Mattermost server version and OS are you using?

**Comment by hajowieland** [comment]
@amyblais 

**Mattermost:** 5.21.0
**OS:** Kubernetes, deployed with Mattermost Enterprise Helm Chart
**DB:** AWS RDS (PostgreSQL 9.6.16)

**Comment by icelander** [comment]
@hajowieland 

The SAML IdP certificate file is renamed to `saml-idp.crt` when it's stored in the database, so your config file should use that for the filename.

To further diagnose the error we need to see the query that Mattermost is loading out of the database. Run this query against your database to see the file contents.

```sql
SELECT Data FROM ConfigurationFiles WHERE Name = 'saml-idp.crt';
```

It should return a value that matches the certificate you uploaded. If it doesn't, try uploading it again while watching the logs for errors.

**Comment by hajowieland** [comment]
@icelander 

Thanks for your help! The file contents in the database look fine (see **7.**)


### My steps taken:

1. Set  **Identity Provider Metadata URL** to the Metadata URL provided by the Auth0 application's _"SAML2 WebApp"_ Addon

2. Button "Get SAML Metadata From IdP"

3. Adapt Identity Provider Issuer URL: it gets filled from Step 2 with the prefix `urn:tenant.eu.auth0.com`. This is what Auth0 tells us as "Issuer". But if I want to save this Mattermost config, it show the error: `Identity Provider Issuer URL must be a valid URL and start with http:// or https://`.  So I replace `urn:tenant.eu.auth0.com` with `https://tenant.eu.auth0.com`

4. Auth0: **Application Callback URL:** `https://my-mattermost.com/login/sso/saml`

**Settings:**

```
{
  "audience": "https://my-mattermost.comlogin/sso/saml",
  "recipient": "https://my-mattermost.com/login/sso/saml",
  "mappings": {
    "email":       "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
    "name":        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
  }
}
```

5. Mattermost: I set the **Email Attribute:** `email` and  **Username Attribute:** `name`
 
6. When saving the Mattermost SAML Config, it still shows this in the error Log:

```
An error occurred while configuring SAML Service Provider","error":"failed to load idp public certificate: failed to get config file saml-idp.crt: failed to scan data from row for saml-idp.crt: pq: syntax error at end of input","errorVerbose":"pq: syntax error at end of input\nfailed to scan data from row for saml-idp.crt\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).GetFile\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:278\ngithub.com/mattermost/mattermost-server/v5/app.(*App).GetConfigFile\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:359\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:273\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357\nfailed to get config file saml-idp.crt\ngithub.com/mattermost/mattermost-server/v5/app.(*App).GetConfigFile\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:361\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:273\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357\nfailed to load idp public certificate\ngithub.com/mattermost/mattermost-server/v5/enterprise/saml.(*SamlInterfaceImpl).ConfigureSP\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/saml/saml.go:275\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).initEnterprise.func1\n\tgithub.com/mattermost/mattermost-server/v5@/app/enterprise.go:153\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*DatabaseStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/database.go:163\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SaveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:382\ngithub.com/mattermost/mattermost-server/v5/enterprise/cluster.(*GeneralClusterAPI).saveConfig\n\tgithub.com/mattermost/mattermost-server/v5@/enterprise/cluster/general_cluster.go:44\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\ngithub.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\tgithub.com/gorilla/handlers@v1.4.2/recovery.go:78\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357"}
```

7. The SQL Query gives the correct Cert file loaded in the database:

```
SELECT Data FROM ConfigurationFiles WHERE Name = 'saml-idp.crt';
                               data
------------------------------------------------------------------
 -----BEGIN CERTIFICATE-----                                     +
 MIIDAzCCBeugAwIBAgIJbjSMSEA+xjayMA0GCSqGSIb3DQEBCwUAMB8xHTAbBgNV+
 BAMTFHNhdmUtdXAuZXUuYXV0aDAuY29tMB4XDTE3MDUxNzEyMDEzN1oXDTMxMDEy+
 NDEyMDEzN1owHzEdMBsGA1UEAxMUc2F2ZS11cC5ldS5hdXRoMC5jb20wggEiMA0G+
 CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCg2Ty+qLosOp5gC35nnHM0SQp244D9+
 5S7Z6N//TWbOfBFfmQLzcQfQi/2jmC5Z3oDJdMyl0c/EmxHjRNELq0oRnH0cow2Y+
 PaBcIKrzHmKZg8y6mXXFRcsaj5U/zoYZSNeFXzWYbM4zKmUK+sX6NvKnoFcLcKBF+
 rrClDE//uR9W7NJy7noB2JylnoYveAZBFL4vESqX9K6qkrq9GOpmjtE9AYbPkl/4+
 71G3K0l9J7763e4o1QVRI4DDPnMUfHEW27X2oYxw8535NZSg8bA1KH/cIsXxmgYa+
 Mfns8FrhbN8lNOmgcnzdih75GZvZjVrAvmg3+OCCTIohjW65ZHkxKEvpAgMBAAGj+
 QjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKVeoQ84Vnz385sbP0w9LYjM+
 m1U3MA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0BAQsFAAOCAQEAaZY93oqtcjCl+
 /r5VKL+JMI985T95zgsjtwkB3jn21p/zWpv4ff0QdKf5JVJ0RD4DNHhZKxJ0Fkkg+
 FzYxBgFrA9VGNAW2blxsHmp18WWtYlASREA0fDmrRA4WbIFjOh3oTPK7sFpH6tk8+
 IUPx0ldOFJEbXe2bGeYnb8w4cDlFq9b7YnBH1eAmLw2VZyDZfBuasyi/ijYYBOoe+
 Elraae37u25Hx98uQCz5vl2lmz+OcLE//ElOaXxX//MTQrbVViwWGpeOjVAmwuwN+
 tqQ3AvGdWBmklMr8dn//dpdK1zcfdW7v//WNV1tn+BIkLMEwjR8JJPZW62kaPLEF+
 xuyowKORkQ==                                                    +
 -----END CERTIFICATE-----                                       +

(1 row)
````

When trying to login via SAML now, it shows the Auth0 login screen and then Mattermost shows `Error Invalid state` in the Web frontend.

The Mattermost log shows:

```
{"level":"debug","ts":1585646990.769839,"caller":"web/handlers.go:79","msg":"Received HTTP request","method":"POST","url":"/login/sso/saml","request_id":"3syn5fhddfyp9nuh8cdwberger"}
{"level":"error","ts":1585646990.7708514,"caller":"mlog/log.go:175","msg":"Invalid state","path":"/login/sso/saml","request_id":"3syn5fhddfyp9nuh8cdwberger","ip_addr":"192.168.226.64","user_id":"","method":"POST","err_where":"completeSaml","http_code":302,"err_details":"illegal base64 data at input byte 148"}
```

**Comment by catalintomai** [comment]
This looks similar to a Postgres-related issue that was likely fixed in 5.22 (part of the changes for https://github.com/mattermost/mattermost-server/pull/13678/files?file-filters%5B%5D=.conf&file-filters%5B%5D=.go - the config/database.go changes).

**Comment by hajowieland** [comment]
@catalintomai thx for helping me out.

Even with the most-recent Mattermost version **5.22.3**, I still get an "Invalid state" error when trying to log in via Auth0:


`{"level":"error","ts":1589444776.7644777,"caller":"mlog/log.go:175","msg":"Invalid state","path":"/login/sso/saml","request_id":"698h15z98jfcxmapcz3zs3hefe","ip_addr":"188.195.158.78","user_id":"","method":"POST","err_where":"completeSaml","http_code":302,"err_details":"illegal base64 data at input byte 148"}`


Any ideas ?

**Comment by catalintomai** [comment]
> completeSaml

From what  I can see, it is a different, later-stage error , don't think we've seen it before, for some reason we fail to decode the RelayState token received from the IdP (see step 5 in https://en.wikipedia.org/wiki/SAML_2.0). Might be helpful to share the value you observe being shared around, maybe it got lost/corrupted somewhere along the way.

**Comment by hajowieland** [comment]
@catalintomai 

Sure, what exact value should I share with you ?

**Comment by amyblais** [comment]
Closing as this is an old issue, but feel free to re-open if it still reproduces,
