### ISSUE TITLE
Direct Messages randomly disappearing in Mattermost

### ISSUE THREAD

**Issue by applic8-sa** [mattermost/mattermost-server#14382]
#### Summary
Direct Messages are randomly disappearing from Mattermost chat window for some users and not others. Sometimes new incoming messages are visible in the OS notification (MacOS X) but not in Mattermost Direct Messages chat window.

Logout from Mattermost Client and login again make them reappear randomly depend on the session and/or the device used (MacOS X client or Mattermosft for iOS or Android). Couple of weeks later the problem of missing messages is back related to session or after a Mattermost server update.

#### Steps to reproduce
We are using Mattermost since 2016 without any major issue.
Beginning of 2019 (February), we upgraded Mattermost from 
mattermost-team-4.7.2 to mattermost-team-5.13.0 and the above
issue started to appear.

#### Expected behavior
UserA should see the same direct messages with userB than userB with UserA

Direct Messages between UserA and UserB should be visible by both.
Incoming Mattermost messages that are displayed in MacOS X notification
should also be displayed in the Direct Messages section of Mattermost Client
for MacOS X with the same direct messages visible at each of the end points.

#### Observed behavior (that appears unintentional) 
Some of the direct nessages of UserA are displayed in Direct Messages
in UserB client some not. Like a split brain effect.

If UserA or UserB logout from Mattermost client and reinstall it 
some direct message reappear some not and sometimes not 
the same messages are hidden and visible.

Point in time Day 1 @ 12:00 (point of view UserA)
UserA: test1
UserB: test2 <-- hidden from Direct Messages of UserA but visible in UserB window
UserA: test3
UserB: test4

Point in time Day 2 @ 14:00 (point of view UserA)
UserA: test1
UserB: test2
UserA: test3
UserB: test4 <-- hidden from Direct Messages of UserA but visible in UserB window

Point in time Day 3 @ 08:00 (point of view UserA)
UserA: test1
UserB: test2 <-- hidden from Direct Messages of UserA but visible in UserB window
UserA: test3
UserB: test4

Detect if the problem is present in your database:
`
SELECT c1.name FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name ORDER BY c1.name;
`

#### Possible fixes
After looking into the database, I found duplicate channels with the same
"UserA-ID__UserB-ID" as channels.name but with different channels.id

The workaround is to remove duplicate channels for Direct Messages

`
SELECT 'UPDATE posts SET channelid = ''' || c1.id || ''' WHERE channelid = ''' || c2.id || '''; DELETE FROM channels WHERE id = ''' || c2.id || ''' AND name = ''' || c2.name || ''';' AS SQL FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name AND c1.createat < c2.createat ORDER BY c1.name, c1.createat;
`

The above SQL generates fix for the issue for posts table
`
UPDATE posts SET channelid = 'kt9igbg37fbyzbxgnsqmasqj7a' WHERE channelid = 'zazhqpsqm7b8bknyk3cq3p1n5a';
DELETE FROM channels WHERE id = 'zazhqpsqm7b8bknyk3cq3p1n5a' AND name = '1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy';
`

The above SQL queries had fixed our issue.

We decided to only modify posts (change channelid) and 
channels (delete one of the two channels with same name) tables

We did not modify channelid in the following tables:
- channelmemberhistory
- channelmembers
- groupchannels
- commandwebhooks
- incomingwebhooks
- outgoingwebhooks

The only side effect so far is that the user need to add again the other user in Direct Messages to see all the messages and the above SQL statement act like a merge of the two channels used as Direct Messages pipeline between the two users.

**Comment by applic8-sa** [comment]
The direct message visible in MacOS X notification is not displayed in the current Direct Message between the two users
![chat](https://user-images.githubusercontent.com/14995404/80394885-c3dfc600-88b2-11ea-83fd-18e97be1e213.png)

Both messages should be part of the same channel to be displayed by both UserA and UserB
![hidden_message](https://user-images.githubusercontent.com/14995404/80394879-c2160280-88b2-11ea-87ff-83f516036eb6.png)

This is the result of
`
SELECT c1.name FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name ORDER BY c1.name;
`
![duplicate_channels](https://user-images.githubusercontent.com/14995404/80394882-c3472f80-88b2-11ea-9e69-23f15ed1fa11.png)

The workaround is to relocate the posts (Direct Messages) from the newer channel to the old one
and then delete the new channel (duplicate with same UserA-ID__UserB-ID pair)
`
SELECT 'UPDATE posts SET channelid = ''' || c1.id || ''' WHERE channelid = ''' || c2.id || '''; DELETE FROM channels WHERE id = ''' || c2.id || ''' AND name = ''' || c2.name || ''';' AS SQL FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name AND c1.createat < c2.createat ORDER BY c1.name, c1.createat;
`

**Comment by amyblais** [comment]
@applic8-sa Our supported server versions include v5.19.0 or higher. Would you be open to upgrading? 
Also, are you on desktop app or webapp?

**Comment by applic8-sa** [comment]
We are already running the latest version as of today and the problem was not fixed by the upgrade
so I did the workaround above and it fixed our issue of duplicate Direct Messages "ghost" channels

Mattermost Version: 5.22.1
Database Schema Version: 5.22.0
Database: postgres

**Comment by applic8-sa** [comment]
I still have the backup of database before the above fix (5.22.1) but I don't have the backup of 2019-02-09 when the problem occured during the upgrade between 4.7.x and 5.13.x. It's about a year that we have this missing message missing in Direct Messages, we were about to change product before I found the above fix as a chat system with random direct messages not working is not very useful. Private and Public channels were working fine.

**Comment by applic8-sa** [comment]
If you run a Mattermost servers which has been upgraded through years (2016-2020) you can check if you have the same kind of issue without known it by executing the following SQL
`
SELECT c1.name FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name ORDER BY c1.name;
`
If it returns some duplicate pairs... that mean you have hidden Direct Messages for some of your user base and they will not able to read them depend on their session.

**Comment by agnivade** [comment]
Thank you for the very detailed report !

I have filed https://mattermost.atlassian.net/browse/MM-24626 to track it.

**Comment by wiggin77** [comment]
This appears to be an issue with the upgrade path.  A probable solution is provided here:  https://mattermost.atlassian.net/browse/MM-19203

**Comment by agnivade** [comment]
Hi @applic8-sa, as @wiggin77 correctly pointed out, this issue seems to be a corner-case bug in our DB schema upgrade path which can happen if someone upgrades from a very old version to a new version. From your initial comment

> Beginning of 2019 (February), we upgraded Mattermost from
mattermost-team-4.7.2 to mattermost-team-5.13.0 and the above
issue started to appear.

that does indeed seem to be the case.

The solution is given in the JIRA ticket which would be to apply the missing indexes. The solution that you have done correctly mitigates the current issue, by de-duplicating the channels. But for a long-term solution, it is recommended to match the DB schema to what the latest version correctly expects.

**Comment by applic8-sa** [comment]
Hi @agnivade, 

Do you have a tool to check the consistency of the current postgresql schema for mattermost database against the spec of the version (Database Schema Version: 5.22.0)?
If not where can I find the schema for 5.22.0 version to compare it?

Where can I find the ALTER TABLE for the missing indexes?

The alternative might be to do a pg_dump of the current db, install mattermost from scratch inside a new database use again pg_dump and merge the two dumps for CREATE TABLE etc. but not the data.

Thanks for your help.

**Comment by agnivade** [comment]
Yes, mostly what you said. You can create the 5.22 schema by starting the same mattermost instance and pointing to a dummy DB.

To get the diff of the schemas, please see this comment:
https://mattermost.atlassian.net/browse/MM-19203?focusedCommentId=69371

And then if you have any questions on what indexes are safe to add/remove, see:
https://mattermost.atlassian.net/browse/MM-19203?focusedCommentId=69503

Hope that helps.

**Comment by applic8-sa** [comment]
I did a schema dump of a docker instance to get the valid 5.22 schema and I did the same on our server (not docker based). diff does not help as they are not ordered the same way. I will check the comments on the ticket 19203.

# Docker instance
docker exec -it $(docker ps | awk '/mattermost_db/ { print $1 }') bash -c 'PGPASSWORD=${POSTGRES_PASSWORD} pg_dump -U ${POSTGRES_USER} -w -c -s ${POSTGRES_DB}' > mattermost-docker.sql

# Virtual Machine instance
sudo -n -i -u postgres /usr/bin/pg_dump -U postgres -w -c -s mattermost > mattermost-server.sql

diff -Naur mattermost-server.sql mattermost-docker.sql | less

[mattermost-schema.zip](https://github.com/mattermost/mattermost-server/files/4645533/mattermost-schema.zip)

**Comment by applic8-sa** [comment]
So "This is the way" ... to compare it

```
docker exec -it $(docker ps | awk '/mattermost_db/ { print $1 }') bash -c 'PGPASSWORD=${POSTGRES_PASSWORD} psql -U ${POSTGRES_USER} -t -A -c "\dt" ${POSTGRES_DB} | cut -d"|" -f2 | sort | xargs -n 1 -I {} pg_dump -U ${POSTGRES_USER} -w -c -s -t {} ${POSTGRES_DB}' > mattermost-docker.sql

sudo -n -i -u postgres psql -U postgres -t -A -c "\dt" mattermost | cut -d"|" -f2 | sort | xargs -n 1 -I {} sudo -n -i -u postgres pg_dump -U postgres -w -c -s -t {} mattermost > mattermost-server.sql

diff -Naur <(cat mattermost-docker.sql | tr -d '\r' | grep -v -e '^--' -e '^SET ') <(cat mattermost-server.sql | tr -d '\r' | grep -v -e '^--' -e '^SET ')
```

The result is the following as you can see years of migration of Mattermost schema is not perfect
```diff
--- /dev/fd/63	2020-05-18 20:13:41.232209554 +0200
+++ /dev/fd/62	2020-05-18 20:13:41.232209554 +0200
@@ -44,10 +44,10 @@
     userid character varying(26) NOT NULL,
     description character varying(1024),
     ownerid character varying(190),
-    lasticonupdate bigint,
     createat bigint,
     updateat bigint,
-    deleteat bigint
+    deleteat bigint,
+    lasticonupdate bigint
 );
 
 
@@ -491,11 +491,11 @@
 CREATE TABLE public.groupchannels (
     groupid character varying(26) NOT NULL,
     autoadd boolean,
-    schemeadmin boolean,
     createat bigint,
     deleteat bigint,
     updateat bigint,
-    channelid character varying(26) NOT NULL
+    channelid character varying(26) NOT NULL,
+    schemeadmin boolean DEFAULT false
 );
 
 
@@ -559,11 +559,11 @@
 CREATE TABLE public.groupteams (
     groupid character varying(26) NOT NULL,
     autoadd boolean,
-    schemeadmin boolean,
     createat bigint,
     deleteat bigint,
     updateat bigint,
-    teamid character varying(26) NOT NULL
+    teamid character varying(26) NOT NULL,
+    schemeadmin boolean DEFAULT false
 );
 
 
@@ -607,9 +607,9 @@
     teamid character varying(26),
     displayname character varying(64),
     description character varying(500),
-    username text,
-    iconurl text,
-    channellocked boolean
+    username character varying(64) DEFAULT ''::character varying,
+    iconurl character varying(1024) DEFAULT ''::character varying,
+    channellocked boolean DEFAULT false
 );
 
 
@@ -751,7 +751,7 @@
     refreshtoken character varying(26),
     redirecturi character varying(256),
     expiresat bigint,
-    scope character varying(128)
+    scope character varying(128) DEFAULT 'user'::character varying
 );
 
 
@@ -957,21 +957,21 @@
     id character varying(26) NOT NULL,
     createat bigint,
     updateat bigint,
-    editat bigint,
     deleteat bigint,
-    ispinned boolean,
     userid character varying(26),
     channelid character varying(26),
     rootid character varying(26),
     parentid character varying(26),
-    originalid character varying(26),
-    message character varying(65535),
+    originalid text,
+    message character varying(4000),
     type character varying(26),
     props character varying(8000),
     hashtags character varying(1000),
     filenames character varying(4000),
-    fileids character varying(150),
-    hasreactions boolean
+    fileids character varying(150) DEFAULT '[]'::character varying,
+    hasreactions boolean DEFAULT false,
+    editat bigint DEFAULT (0)::bigint,
+    ispinned boolean DEFAULT false
 );
 
 
@@ -1135,6 +1135,9 @@
 
 SELECT pg_catalog.set_config('search_path', '', false);
 
+DROP INDEX public.idx_reactions_user_id;
+DROP INDEX public.idx_reactions_post_id;
+DROP INDEX public.idx_reactions_emoji_name;
 ALTER TABLE ONLY public.reactions DROP CONSTRAINT reactions_pkey;
 DROP TABLE public.reactions;
 
@@ -1152,7 +1155,19 @@
 
 
 ALTER TABLE ONLY public.reactions
-    ADD CONSTRAINT reactions_pkey PRIMARY KEY (postid, userid, emojiname);
+    ADD CONSTRAINT reactions_pkey PRIMARY KEY (userid, postid, emojiname);
+
+
+
+CREATE INDEX idx_reactions_emoji_name ON public.reactions USING btree (emojiname);
+
+
+
+CREATE INDEX idx_reactions_post_id ON public.reactions USING btree (postid);
+
+
+
+CREATE INDEX idx_reactions_user_id ON public.reactions USING btree (userid);
 
 
 
@@ -1217,9 +1232,9 @@
     scope character varying(32),
     defaultteamadminrole character varying(64),
     defaultteamuserrole character varying(64),
+    defaultteamguestrole character varying(64),
     defaultchanneladminrole character varying(64),
     defaultchanneluserrole character varying(64),
-    defaultteamguestrole character varying(64),
     defaultchannelguestrole character varying(64)
 );
 
@@ -1319,8 +1334,8 @@
 CREATE TABLE public.status (
     userid character varying(26) NOT NULL,
     status character varying(32),
-    manual boolean,
-    lastactivityat bigint
+    lastactivityat bigint,
+    manual boolean DEFAULT false
 );
 
 
@@ -1429,15 +1444,15 @@
     deleteat bigint,
     displayname character varying(64),
     name character varying(64),
-    description character varying(255),
     email character varying(128),
     type text,
     companyname character varying(64),
     alloweddomains character varying(1000),
     inviteid character varying(32),
     allowopeninvite boolean,
-    lastteamiconupdate bigint,
-    schemeid text,
+    description character varying(255) DEFAULT ''::character varying,
+    lastteamiconupdate bigint DEFAULT (0)::bigint,
+    schemeid character varying(26),
     groupconstrained boolean
 );
 
@@ -1546,7 +1561,7 @@
     token character varying(26),
     userid character varying(26),
     description character varying(512),
-    isactive boolean
+    isactive boolean DEFAULT true
 );
 
 
@@ -1662,7 +1677,6 @@
     nickname character varying(64),
     firstname character varying(64),
     lastname character varying(64),
-    "position" character varying(128),
     roles character varying(256),
     allowmarketing boolean,
     props character varying(4000),
@@ -1671,9 +1685,10 @@
     lastpictureupdate bigint,
     failedattempts integer,
     locale character varying(5),
-    timezone character varying(256),
     mfaactive boolean,
-    mfasecret character varying(128)
+    mfasecret character varying(128),
+    "position" character varying(128) DEFAULT ''::character varying,
+    timezone character varying(256) DEFAULT '{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"}'::character varying
 );
```

What do you recommend us to do?

**Comment by applic8-sa** [comment]
With a bigger context (-U30) you can also see the name of the tables

```
diff -NarU30 <(cat mattermost-docker.sql | tr -d '\r' | grep -v -e '^--' -e '^SET ') <(cat mattermost-server.sql | tr -d '\r' | grep -v -e '^--' -e '^SET ') > mattermost-schema.diff
```

[mattermost-schema.zip](https://github.com/mattermost/mattermost-server/files/4645915/mattermost-schema.zip)

**Comment by applic8-sa** [comment]
Findings
- A lot of default value has been dropped in the new schema (still present in our schema)
- Some character varying has been converted to text
- Some character varying has been increased
- Some indexes had been dropped for reactions idx_reactions_emoji_name, idx_reactions_post_id, idx_reactions_user_id
- reactions_pkey constraint has been dropped

I don't know the impact of the above.

``` diff
grep '^[+-]' mattermost-schema.diff | sort -k2 | grep -v -P '^([+-]{3}|-$)'+    ADD CONSTRAINT reactions_pkey PRIMARY KEY (postid, userid, emojiname);
-    ADD CONSTRAINT reactions_pkey PRIMARY KEY (userid, postid, emojiname);
+    channelid character varying(26) NOT NULL
-    channelid character varying(26) NOT NULL,
+    channellocked boolean
-    channellocked boolean DEFAULT false
+    defaultteamguestrole character varying(64),
-    defaultteamguestrole character varying(64),
+    deleteat bigint
-    deleteat bigint,
+    description character varying(255),
-    description character varying(255) DEFAULT ''::character varying,
+    editat bigint,
-    editat bigint DEFAULT (0)::bigint,
+    fileids character varying(150),
-    fileids character varying(150) DEFAULT '[]'::character varying,
+    hasreactions boolean
-    hasreactions boolean DEFAULT false,
-    iconurl character varying(1024) DEFAULT ''::character varying,
+    iconurl text,
-CREATE INDEX idx_reactions_emoji_name ON public.reactions USING btree (emojiname);
-CREATE INDEX idx_reactions_post_id ON public.reactions USING btree (postid);
-CREATE INDEX idx_reactions_user_id ON public.reactions USING btree (userid);
-DROP INDEX public.idx_reactions_emoji_name;
-DROP INDEX public.idx_reactions_post_id;
-DROP INDEX public.idx_reactions_user_id;
+    isactive boolean
-    isactive boolean DEFAULT true
+    ispinned boolean,
-    ispinned boolean DEFAULT false
+    lastactivityat bigint
-    lastactivityat bigint,
-    lasticonupdate bigint
+    lasticonupdate bigint,
+    lastteamiconupdate bigint,
-    lastteamiconupdate bigint DEFAULT (0)::bigint,
+    manual boolean,
-    manual boolean DEFAULT false
-    message character varying(4000),
+    message character varying(65535),
+    mfasecret character varying(128)
-    mfasecret character varying(128),
+    originalid character varying(26),
-    originalid text,
+    "position" character varying(128),
-    "position" character varying(128) DEFAULT ''::character varying,
+    schemeadmin boolean,
+    schemeadmin boolean,
-    schemeadmin boolean DEFAULT false
-    schemeadmin boolean DEFAULT false
-    schemeid character varying(26),
+    schemeid text,
+    scope character varying(128)
-    scope character varying(128) DEFAULT 'user'::character varying
+    teamid character varying(26) NOT NULL
-    teamid character varying(26) NOT NULL,
+    timezone character varying(256),
-    timezone character varying(256) DEFAULT '{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"}'::character varying
-    username character varying(64) DEFAULT ''::character varying,
+    username text,
```

**Comment by agnivade** [comment]
@lieut-data - do you have any recommendations here since you handled the last ticket.

**Comment by lieut-data** [comment]
@applic8-sa, sorry for the trouble you've encountered. In the issue linked above ([MM-19203](https://mattermost.atlassian.net/browse/MM-19203)), the crux of the problem lay in the missing `channels_name_teamid_key` index: this index guarantees that two channels with the same `Name` and `TeamId` cannot exist in the `Channels` table.

Unexpectedly, your `mattermost-server.sql` dump already contains this index, yet the queries above show the index being violated. Can you check the `TeamId` values for the rows in question? They should be empty for all direct messages.

@agnivade & @wiersgallak, unfortunately I can't think of a great way to solve this problem "in-product". It's unfortunate that our older migration strategy wasn't robust, leading to a significant lag before issues like these crop up. Might we consider an effort to document the schema rebuilding strategy hinted at earlier? i.e., ideally we'd have MySQL and Postgres instructions on how to spin up an empty schema and then import a dump of data from the older schema. This would be a place to document any special cases that might need to be handled.

**Comment by applic8-sa** [comment]
> Can you check the TeamId values for the rows in question? 
> They should be empty for all direct messages.

sure.

I did a restoration of the backup before my fix of the duplicate channels.

so teamid is sometimes empty ('') sometimes definied with something but never NULL

``` sql
SELECT c1.name, c1.teamid, c2.teamid 
FROM channels AS c1, channels AS c2 
WHERE c1.id <> c2.id AND c1.name = c2.name 
ORDER BY c1.name;

                          name                          |           teamid           |           teamid           
--------------------------------------------------------+----------------------------+----------------------------
 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba |                            | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba | xg9ewfanpiy79dm451k9kan8uy | 
 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque | xg9ewfanpiy79dm451k9kan8uy | 
 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque |                            | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y |                            | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y | xg9ewfanpiy79dm451k9kan8uy | 
 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y | xg9ewfanpiy79dm451k9kan8uy | 
 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y |                            | xg9ewfanpiy79dm451k9kan8uy
 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
 h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
 h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
 j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y |                            | xg9ewfanpiy79dm451k9kan8uy
 md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y | xg9ewfanpiy79dm451k9kan8uy | 
 ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c | xg9ewfanpiy79dm451k9kan8uy | 
 ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c |                            | xg9ewfanpiy79dm451k9kan8uy
 ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
 ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy | xg9ewfanpiy79dm451k9kan8uy | 
 qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy |                            | xg9ewfanpiy79dm451k9kan8uy
(24 rows)

SELECT c1.name, c1.teamid, c2.teamid FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name AND c1.teamid IS NULL ORDER BY c1.name;
 name | teamid | teamid 
------+--------+--------
(0 rows)

SELECT c1.name, c1.teamid, c2.teamid FROM channels AS c1, channels AS c2 WHERE c1.id <> c2.id AND c1.name = c2.name AND c1.teamid = '' ORDER BY c1.name;
                          name                          | teamid |           teamid           
--------------------------------------------------------+--------+----------------------------
 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba |        | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque |        | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y |        | xg9ewfanpiy79dm451k9kan8uy
 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y |        | xg9ewfanpiy79dm451k9kan8uy
 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
 h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
 j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
 md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y |        | xg9ewfanpiy79dm451k9kan8uy
 ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c |        | xg9ewfanpiy79dm451k9kan8uy
 ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
 qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy |        | xg9ewfanpiy79dm451k9kan8uy
(12 rows)
```

**Comment by applic8-sa** [comment]
Since I did the fix in the current production database, the problem is back for one user
so there is something strang with the way the teamid works in our mattermost

``` sql
SELECT c1.name, c1.teamid, c2.teamid 
FROM channels AS c1, channels AS c2 
WHERE c1.id <> c2.id AND c1.name = c2.name 
ORDER BY c1.name;

                          name                          |           teamid           |           teamid           
--------------------------------------------------------+----------------------------+----------------------------
 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de | xg9ewfanpiy79dm451k9kan8uy | 
 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de |                            | xg9ewfanpiy79dm451k9kan8uy
(2 rows)
```

**Comment by lieut-data** [comment]
Ah, interesting. The cross join confused me at first: the unique index isn't actually being violated, it's just that one row has a `TeamID` assigned and another leaves it empty. Another way to see this might be:
```sql
SELECT c1.Id, c2.Id, c1.Name, c1.TeamId, c2.TeamId FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
```

This is definitely a distinct issue than an old schema migration -- the Mattermost server shouldn't write a `TeamID` when saving a direct channel. I took a quick glance through the code, and confirmed that direct message channels are created without assigning a team.

Can you tell me anything more about your environment? Any kind of periodic import occurring? Any custom plugins?

**Comment by applic8-sa** [comment]
> Can you tell me anything more about your environment? 

Our Mattermost is behind a firewall with no outbound access and a NAT 1:1
Some users connects via the public IP of the mattermost server instance (Trusted source IP)
Some users connects via the private IP of the mattermost server instance (via VPN)

After we had this kind of issue, we asked all our users to stop using Mattermost
on their mobile phone (iOS / Android) as initially we had the feeling the root cause
might be linked to the user connect via two devices.

Our users are using Mattermost via the Mac Application application
and sometimes via Chrome on a Chromebook (Mattermost is not available on it)

> Any kind of periodic import occurring? Any custom plugins?

We had no plugins nor webhooks before and during the migration from 4.x to 5.x
Since about a week we have just Jitsi and Remind Bot.

``` sql
SELECT c1.Id, c2.Id, c1.Name, c1.TeamId, c2.TeamId FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
             id             |             id             |                          name                          | teamid |           teamid           
----------------------------+----------------------------+--------------------------------------------------------+--------+----------------------------
 8x4igmemkjghjk66ku1o7tyk5e | pozsig6ir7fzipdgd1abqr9jry | 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de |        | xg9ewfanpiy79dm451k9kan8uy
(1 row)
```

**Comment by lieut-data** [comment]
@agnivade, see above for a different tangent, but this no longer appears to be the same issue as https://mattermost.atlassian.net/browse/MM-19203. We need to get to the bottom of why some direct message channels are being created (or updated?) with a `TeamID`. We could probably stand to make this part of the business logic more robust in other ways as well.

**Comment by applic8-sa** [comment]
Another info, one the two users in the above duplicate Direct Channel 
is using Mattermost 4.4.1 client for Mac (not the latest 4.4.2)

We have almost the latest version of Mattermost server (5.22.2) 
and database schema (5.22.0)

I will upgrade to 5.23.0.

**Comment by agnivade** [comment]
@lieut-data - Thanks for giving a hand here. I must confess I have not followed the entire thread very closely and don't remember everything. But I am trying to understand if this TeamID appearing in direct channels is the cause or the symptom. And how does it relate to multiple direct channels with the same ID, having the same name ? Is one causing the other ? Or are they both related ?

In any case, perhaps this warrants a fresh ticket to be created ? Since the old one got muddied with the previous context.

**Comment by lieut-data** [comment]
@agnivade, I suspect the `TeamID` in the direct channels is a cause, in that the server assumes it can rely on the `channels_name_teamid_key` unique constraint. If we can create direct messages and assign them to teams, we allow a direct message per team, and the symptoms above would likely all manifest. Using the force here.

0/5 on repurposing the existing ticket or starting a new one, but I'll start by adding a note to MM-24626 in the hopes of capturing this detail.

**Comment by agnivade** [comment]
Sounds good. I think we can reopen the existing one then.

**Comment by applic8-sa** [comment]
More about our setup and timeline:

Back in 2016, we created two Teams one per country but the limitation of Mattermost at that time was that could not communicate between user not member of the current team. So we switch to a single Team called "applic8". In 2018, a second Team has been created to discuss with an external partner and we removed it. In 2019 before upgrading the OS, we jumped from mattermost 4.7.2 to 5.13.0 and this issue started. In 2020, I managed to track the split brain (alternative reality) Direct Messages by spoting that messages in notification are not present in the current Direct Messages of the users and found them in the database under different Direct Channels one with TeamID = '' one with the TeamID used by all our users.

**Comment by streamer45** [comment]
Hi @applic8-sa,
I am taking a look at this issue. I am wondering if you could provide a bit more data for the duplicated channels. I am mainly interested in time fields `CreateAt` and `UpdateAt` but a full select for those rows would be ideal.

**Comment by applic8-sa** [comment]
@streamer45

Before the fix (2020-04-27)
``` sql
SELECT c1.name, c1.createat, c1.updateat, c2.createat, c2.updateat FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
                          name                          |   createat    |   updateat    |   createat    |   updateat    
--------------------------------------------------------+---------------+---------------+---------------+---------------
 ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy | 1474909109967 | 1474909109967 | 1551177481053 | 1551177481053
 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y | 1475073200015 | 1475073200015 | 1550734882797 | 1550734882797
 ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c | 1550592412600 | 1550592412600 | 1474907237742 | 1474907237742
 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque | 1474908043347 | 1474908043347 | 1552313817492 | 1552313817492
 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y | 1472553205190 | 1472553205190 | 1552290333255 | 1552290333255
 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy | 1550822942816 | 1550822942816 | 1474907796901 | 1474907796901
 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba | 1557215998290 | 1557215998290 | 1474876436430 | 1474876436430
 j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy | 1474908046051 | 1474908046051 | 1550645379595 | 1550645379595
 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy | 1474877402502 | 1474877402502 | 1550645424035 | 1550645424035
 qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy | 1551146497492 | 1551146497492 | 1474908519479 | 1474908519479
 md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y | 1550734880934 | 1563376573577 | 1474906772439 | 1563432269399
 h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy | 1474908244753 | 1565331566982 | 1550744785560 | 1550744785560
(12 rows)

SELECT c1.*, c2.* FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
                          name                          |             id             |   createat    |   updateat    | deleteat |           teamid           | type | displayname |                          name                          | header | purpose |  lastpostat   | totalmsgcount | extraupdateat | creatorid | schemeid | groupconstrained |             id             |   createat    |   updateat    | deleteat |           teamid           | type | displayname |                          name                          | header | purpose |  lastpostat   | totalmsgcount | extraupdateat | creatorid | schemeid | groupconstrained 
--------------------------------------------------------+----------------------------+---------------+---------------+----------+----------------------------+------+-------------+--------------------------------------------------------+--------+---------+---------------+---------------+---------------+-----------+----------+------------------+----------------------------+---------------+---------------+----------+----------------------------+------+-------------+--------------------------------------------------------+--------+---------+---------------+---------------+---------------+-----------+----------+------------------
 ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy | b6wk7a8pktns8gcxs8tjxc1rge | 1474909109967 | 1474909109967 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1585038537558 |         15972 | 1474909109967 |           |          |                  | tfoetjdsdbbefkakftwgtcb6da | 1551177481053 | 1551177481053 |        0 |                            | D    |             | ns7abwccjjbqjg1s711z5pig1y__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587968668817 |           898 | 1551177481053 |           |          | 
 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y | qhoiq9nu7iy6bbxantx9m6fnzo | 1475073200015 | 1475073200015 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y |        |         | 1585209695261 |          2074 | 1475073200015 |           |          |                  | stmikwby1tditm87ftpe4csyah | 1550734882797 | 1550734882797 |        0 |                            | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__ns7abwccjjbqjg1s711z5pig1y |        |         | 1587039782634 |           321 | 1550734882797 |           |          | 
 ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c | 9yidya4qs7bdtxgx5nc74xmiyo | 1550592412600 | 1550592412600 |        0 |                            | D    |             | ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c |        |         | 1581687607090 |             9 | 1550592412600 |           |          |                  | zw1n9ggz63gtigw63xbf5weuiy | 1474907237742 | 1474907237742 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | ns7abwccjjbqjg1s711z5pig1y__nuxpdghjjbbgf8foza1unccb3c |        |         | 1586964730993 |          1747 | 1474907237742 |           |          | 
 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque | 5iqb1bxm6jrbp8mdfea7o1no6c | 1474908043347 | 1474908043347 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque |        |         | 1571388121235 |           153 | 1474908043347 |           |          |                  | a4e5ktokpff3p8c436n46nf6uo | 1552313817492 | 1552313817492 |        0 |                            | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__j8fm5cp3w3dq9fb1k7661deque |        |         |             0 |             0 | 1552313817492 |           |          | 
 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y | 5qhd5ty5k7ghbehko764ea8xry | 1472553205190 | 1472553205190 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y |        |         | 1579766504705 |          2677 | 1472553205190 |           |          |                  | fn6eaiuyjff6id1xnowspgw38o | 1552290333255 | 1552290333255 |        0 |                            | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__ns7abwccjjbqjg1s711z5pig1y |        |         | 1587973116982 |           438 | 1552290333255 |           |          | 
 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy | kzpmza48h7r7j8jq7ot33bjy3w | 1550822942816 | 1550822942816 |        0 |                            | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587977719158 |            84 | 1550822942816 |           |          |                  | xtmkg3kw8inqbqh11q75dc8psw | 1474907796901 | 1474907796901 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1571800021964 |          2786 | 1474907796901 |           |          | 
 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba | 7ixenfsza784im8outi135gu1a | 1557215998290 | 1557215998290 |        0 |                            | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba |        |         | 1587975320591 |            28 | 1557215998290 |           |          |                  | m7gpj4xjx78t3crd8bue3ifkcw | 1474876436430 | 1474876436430 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__guo7poqddtnu5gtqnum6j774ba |        |         | 1586942571909 |           871 | 1474876436430 |           |          | 
 j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy | 7q1gw9e96igm3psyuyykpbznky | 1474908046051 | 1474908046051 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1586844656123 |           945 | 1474908046051 |           |          |                  | ik77gfzme7gotxyramdx35hb5c | 1550645379595 | 1550645379595 |        0 |                            | D    |             | j8fm5cp3w3dq9fb1k7661deque__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587979899540 |            47 | 1550645379595 |           |          | 
 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy | kt9igbg37fbyzbxgnsqmasqj7a | 1474877402502 | 1474877402502 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587978095856 |          3735 | 1474877402502 |           |          |                  | zazhqpsqm7b8bknyk3cq3p1n5a | 1550645424035 | 1550645424035 |        0 |                            | D    |             | 1k3bsqngojnk7mz1ruxgsqhsqr__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587978077721 |            94 | 1550645424035 |           |          | 
 qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy | f7kgfuzj47d6bnaphckns8p9ko | 1551146497492 | 1551146497492 |        0 |                            | D    |             | qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy |        |         |             0 |             0 | 1551146497492 |           |          |                  | un8e9trx4tbg5c4kp16ikiph1h | 14749
08519479 | 1474908519479 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | qkierrwc4fbnpeg51x7foo7qoy__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1556126131882 |          1202 | 1474908519479 |           |          | 
 md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y | euuhki6rhjgbx81h63mh9yjkxh | 1550734880934 | 1563376573577 |        0 |                            | D    |             | md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y | Damien |         | 1583843823542 |           371 | 1550734880934 |           |          |                  | ufi3rotzzpnwbcm64hbsqhmjbh | 1474906772439 | 1563432269399 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | md7z8oee4b8k7bpjr349ge46de__ns7abwccjjbqjg1s711z5pig1y |        |         | 1587480271027 |         11593 | 1474906772439 |           |          | 
 h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy | 8gokhysu6jgummtyefmn69jgyy | 1474908244753 | 1565331566982 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy | test   |         | 1587030664977 |          1580 | 1474908244753 |           |          |                  | pz7x8kb34ifqbk6e18fibo8roo | 1550744785560 | 1550744785560 |        0 |                            | D    |             | h8wy3manybyuj8snss1t31ez7c__y63oi9bkibd99xmgtm8g6hb7uy |        |         | 1587979943301 |           203 | 1550744785560 |           |          | 
(12 rows)
```

After the fix (now)
``` sql
SELECT c1.name, c1.createat, c1.updateat, c2.createat, c2.updateat FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
                          name                          |   createat    |   updateat    |   createat    |   updateat    
--------------------------------------------------------+---------------+---------------+---------------+---------------
 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de | 1589362000851 | 1589362000851 | 1475052342265 | 1475052342265
(1 row)

SELECT c1.*, c2.* FROM Channels c1 JOIN Channels c2 ON (c1.Type = 'D' AND c1.Id < c2.Id AND c1.Name = c2.Name AND c1.TeamId <> c2.TeamId);
             id             |   createat    |   updateat    | deleteat | teamid | type | displayname |                          name                          | header | purpose |  lastpostat   | totalmsgcount | extraupdateat | creatorid | schemeid | groupconstrained |             id             |   createat    |   updateat    | deleteat |           teamid           | type | displayname |                          name                          | header | purpose |  lastpostat   | totalmsgcount | extraupdateat | creatorid | schemeid | groupconstrained 
----------------------------+---------------+---------------+----------+--------+------+-------------+--------------------------------------------------------+--------+---------+---------------+---------------+---------------+-----------+----------+------------------+----------------------------+---------------+---------------+----------+----------------------------+------+-------------+--------------------------------------------------------+--------+---------+---------------+---------------+---------------+-----------+----------+------------------
 8x4igmemkjghjk66ku1o7tyk5e | 1589362000851 | 1589362000851 |        0 |        | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de |        |         | 1589961460549 |            44 |             0 |           |          |                  | pozsig6ir7fzipdgd1abqr9jry | 1475052342265 | 1475052342265 |        0 | xg9ewfanpiy79dm451k9kan8uy | D    |             | 6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de |        |         | 1589893302351 |          5320 | 1475052342265 |           |          | 
(1 row)
```

**Comment by streamer45** [comment]
According to that data it appears the original channel `pozsig6ir7fzipdgd1abqr9jry` (created in 2016) is the one with the `TeamId` set. In which case it explains why a new channel between the same users could be made.

Did the fix you applied also include setting the `TeamId` to empty for all direct/group channels who had one set?

**Comment by applic8-sa** [comment]
The following fix did not include TeamId as I was not aware of it (the impact / constraint)

My idea was to reattach the new "ghost" messages to the oldest "Direct Messages" channel and delete the newest channel.

The Channel ID pozsig6ir7fzipdgd1abqr9jry is one of the original "Direct Messages" channel created by our users. 

The Channel ID 8x4igmemkjghjk66ku1o7tyk5e is yet another "ghost" channel created/generated AFTER I make the fix bellow so something in our database or in Mattermost App for Mac generates ghost channels with TeamID equal to empty while our old "Direct Messages" channels use the TeamID of our current global Team.

If you confirm that "Direct Channels" should never have TeamID defined to something else than empty (''). The problem could be that at some point in time (I don't recall), I changed all TeamID of all channels to the same one as we had the problem that people member of different teams could not communicate with each other (we need to have chat between team in different countries) and it was somehow not possible back in 2016 so I probably made a merge somehow to have a single TeamID for all. It is possible that Mattermost 5.x did not expect the TeamID to be defined for the original "Direct Messages" channel so it creates new one from time to time.

So should I update all "Direct Messages" channels to TeamID = '' (empty) to fix this issue ?

``` sql
SELECT 'UPDATE posts SET channelid = ''' || c1.id || ''' WHERE channelid = ''' || c2.id || '''; DELETE FROM channels WHERE id = ''' || c2.id || ''' AND name = ''' || c2.name || ''';' AS SQL 
FROM channels AS c1, channels AS c2 
WHERE 
c1.id <> c2.id AND c1.name = c2.name 
AND c1.createat < c2.createat 
ORDER BY c1.name, c1.createat;
```

**Comment by streamer45** [comment]
Yes. Direct and Group channels should have an empty `TeamId` (as in empty string `''`). This will stop duplicates getting created since the `channels_name_teamid_key` will be able to enforce the rule once all values of `TeamId` columns for those channels are empty.

In your specific case I suggest to apply the fix you propose to get rid of the new duplicated channels and then set the `TeamId` for the original channel to empty.

**Comment by applic8-sa** [comment]
Thanks you very much for your help

So at the end, we had an unexpected modification in our mattermost database that combined with something in 5.x server or latest client for Mac create randomly new "Direct Messages" channel or switch between "Direct Messages" channels with empty TeamID and TeamID set. All this made the edge case. 

I assume somewhere in the code, you check TeamID = '' and type 'D' and if none returned, you create a new "Direct Messages" channel and when two "Direct Messages" channels are returned (for a pair of users) you randomly pick the first as there is no ORDER set in the SQL query.

Following the above, I did the following fix in our mattermost database.
(I still have a backup of the original one if you want I check something)
``` sql
SELECT 'UPDATE posts SET channelid = ''' || c1.id || ''' WHERE channelid = ''' || c2.id || '''; DELETE FROM channels WHERE id = ''' || c2.id || ''' AND name = ''' || c2.name || ''';' AS SQL 
FROM channels AS c1, channels AS c2 
WHERE 
c1.id <> c2.id AND c1.name = c2.name 
AND c1.createat < c2.createat 
ORDER BY c1.name, c1.createat;

UPDATE posts SET channelid = 'pozsig6ir7fzipdgd1abqr9jry' WHERE channelid = '8x4igmemkjghjk66ku1o7tyk5e'; 
DELETE FROM channels WHERE id = '8x4igmemkjghjk66ku1o7tyk5e' AND name = '6dj19ewuifyxtfa6axk4hjs95e__md7z8oee4b8k7bpjr349ge46de';
UPDATE 44
DELETE 1

SELECT teamid, type, count(*) FROM channels GROUP BY teamid, type ORDER BY teamid, type;
           teamid           | type | count 
----------------------------+------+-------
                            | D    |   251
                            | G    |   155
 xg9ewfanpiy79dm451k9kan8uy | D    |   148
 xg9ewfanpiy79dm451k9kan8uy | O    |    16
 xg9ewfanpiy79dm451k9kan8uy | P    |   186
(5 rows)

SELECT teamid, type, min(createat), min(updateat) FROM channels GROUP BY teamid, type ORDER BY teamid, type;
           teamid           | type |      min      |      max      |      min      |      max      
----------------------------+------+---------------+---------------+---------------+---------------
                            | D    | 1478072623259 | 1589270399962 | 1478072623259 | 1589270399962
                            | G    | 1489683186865 | 1589989190494 | 1489683186865 | 1589989190494
 xg9ewfanpiy79dm451k9kan8uy | D    | 1472551847384 | 1476088223973 | 1472551847384 | 1565331566982
 xg9ewfanpiy79dm451k9kan8uy | O    | 1472565700986 | 1583424023842 | 1472565700986 | 1583424023842
 xg9ewfanpiy79dm451k9kan8uy | P    | 1472566350915 | 1589963943798 | 1472721137260 | 1589963943798
(5 rows)

UPDATE channels SET teamid = '' WHERE type IN ('D','G');
UPDATE 554

SELECT teamid, type, count(*) FROM channels GROUP BY teamid, type ORDER BY teamid, type;
           teamid           | type | count 
----------------------------+------+-------
                            | D    |   399
                            | G    |   155
 xg9ewfanpiy79dm451k9kan8uy | O    |    16
 xg9ewfanpiy79dm451k9kan8uy | P    |   186
(4 rows)
```

**Comment by streamer45** [comment]
> I assume somewhere in the code, you check TeamID = '' and type = 'D' and if none returned, you create a new "Direct Messages" channel. Or more simple, one of the two user creates again a "Direct Messages" when it is already present in the list (the one with non-empty TeamID). When two "Direct Messages" channels are returned for a pair of users you randomly pick the first as there is no order defined in the SQL query (ORDER BY type, teamid and pick the first will make it more consistent behavior by not switching the session to one or the other).

In the code we don't do any explicit check. We rely on the `channels_name_teamid_key` constraint. 
`TeamId` is set to empty before creating a new direct/group channel and the channel name between the same users will be the same since we compare the users ids lexicographically and always put the *smallest* one in font.

Hopefully this was last action needed to permanently fix the issue but let us know if any of this sort re-appears in the future.

**Comment by lindalumitchell** [comment]
Thanks for this; closing this issue as it appears to have been resolved. Please let us know if anything else comes up with this issue.

**Comment by immolate-d** [comment]
This problem is still happening

Server Version: 5.27.0 (Build 5.27.0)
App Version: 1.39.0 (Build 3000341)
App Platform: android

**Comment by amyblais** [comment]
@immolate-d Would you be open to upgrading to the latest version to see if it still reproduces?

**Comment by DVTrast** [comment]
Hello.
We´ve the same Problem - randomly some direct messages not visible in Mattermost but the post is in the database "Posts".
Server Version: 6.2.1
Desktop-App Version: 5.0.2
App Version: 1.48.2
