### ISSUE TITLE
Emptying first name triggers notification flood

### ISSUE THREAD

**Issue by freayd** [mattermost/mattermost-server#15245]
#### Summary
After emptying your first name, and if it was a word that triggers mentions, you will receive a notification for nearly all new messages.

#### Steps to reproduce
1. Set up a first name under _General Settings > Full Name_
2. Turn on the check box _Notifications > Words That Trigger Mentions > Your case sensitive first name_
3. Delete your _General Settings > Full Name_
4. The checkbox _Words That Trigger Mentions > Your case sensitive first name_ disappeared from the interface
5. Wait for a while until new messages come in.
Mattermost Version: 5.23.1
Database Schema Version: 5.23.0
Database: mysql

#### Expected behavior
The user should only receive notifications for appropriate @ mentions.

#### Observed behavior (that appears unintentional) 
The user will receive notifications for nearly all new messages, including the ones that don't contain mentions or are in threads that he/she didn't participate in.

#### Possible fixes
I'm only guessing here, but it seems that the option _Words That Trigger Mentions > Your case sensitive first name_ remains activated after emptying the first name. Because the name is now an empty string, and basically any message contains an empty string, the user will get flooded with notifications for just about any message. The issue could possibly be fixed if _Words That Trigger Mentions > Your case sensitive first name_ was deactivated when the name is emptied.

**Comment by amyblais** [comment]
@freayd I wasn't able to reproduce on v5.26.0. Is there any additional information that could help me reproduce it?

**Comment by freayd** [comment]
@amyblais Thanks for checking this. I'm not quite sure why can't you reproduce it. At least another user has reported the same issue on the same Mattermost server. Maybe something changed since the version 5.23.1?

Here are some screenshots I took to illustrate the issue.
Received a notification on the IT channel:
![MM1](https://user-images.githubusercontent.com/36454/90327396-cd0db380-dfc5-11ea-97f5-7b9b9f70d97c.png)
The new message does not contain any mention or my previous first name (now emptied), and it marks a new thread (not a reply):
![MM2](https://user-images.githubusercontent.com/36454/90327421-f75f7100-dfc5-11ea-8d2b-80e6e799a915.png)
Notification preferences for the IT channel:
![MM3](https://user-images.githubusercontent.com/36454/90327399-d26afe00-dfc5-11ea-8daf-d574ef7edca7.png)
Account notification settings:
![MM4](https://user-images.githubusercontent.com/36454/90327400-d39c2b00-dfc5-11ea-9758-cbda1ecc783e.png)
Account advanced settings:
![MM5](https://user-images.githubusercontent.com/36454/90327402-d4cd5800-dfc5-11ea-8423-b1e3379d53ae.png)

Not that I'm a MySQL expert, but I know that database configuration can sometimes influence the results of requests. Could this be the case here?

**Comment by amyblais** [comment]
@freayd Would you be open to testing if it reproduces on the latest version? You can test on our community server here: https://community.mattermost.com.

**Comment by freayd** [comment]
@amyblais The server that I use just got upgraded, and I'm sorry to say that the issue is still present. Here are the new versions being used:
> Mattermost Version: 5.26.0
> Database Schema Version: 5.26.0
> Database: mysql

I'll try and see how it behaves on the community server.

**Comment by freayd** [comment]
@amyblais After testing on the community server, I can confirm that the bug is reproducible there too.

**Comment by amyblais** [comment]
Thanks, sorry for the delay, I was off last week. Ticket: https://mattermost.atlassian.net/browse/MM-28447.

**Comment by freayd** [comment]
No worries. Thanks for opening a ticket.

**Comment by amyblais** [comment]
This has been fixed in v5.27, please update when you have a chance,

**Comment by freayd** [comment]
Unfortunately, the issue is still present on the community server, currently running the version 5.27.0.

**Comment by freayd** [comment]
I didn't change any settings on my account there, and still receive notifications for lots of posts.

**Comment by larkox** [comment]
@freayd I think I finally found the bug and was able to solve it. You can track the process in the linked PR.

**Comment by freayd** [comment]
From what I read in the PR, it sounds like this should finally solve the issue. Thanks @larkox.
