### ISSUE TITLE
MTA for Email notifications to Gmail accounts

### ISSUE THREAD

**Issue by dragonpil** [mattermost/mattermost-server#20604]
#### Summary
MTA, from Google for sent Email Notifications because of missing a valid messageId header.
#### Steps to reproduce
Server Version 7.0.1
Writing a message which triggers an email notification to a user with an Gmail account. 

#### Expected behavior
once the Email is sent via SMTP we receive the an MTA from google. 
for example:

> Reporting-MTA: dns; xxxxxx.de
> 
>  Action: failed
> Final-Recipient: rfc822;xxxx@gmail.com
> Status: 5.0.0
> Remote-MTA: dns; gmail-smtp-in.l.google.com
> Diagnostic-Code: smtp; 550-5.7.1 [xxxxxxx] Messages missing a valid messageId header are not
>  550 5.7.1 accepted. h19-20020a05600c351300b003a05634b25esi31213317wmq.147 - gsmtp

#### Observed behavior (that appears unintentional) 
using the same smtp server with the same user with a standard email client a messageID is generated and send and google accepts the message. 
#### Possible fixes
Adding a Message-ID Header to all emails send by mattermost should solve the issue.

**Comment by streamer45** [comment]
Hi @dragonpil,

a couple of questions:

- Could you confirm whether the message-id is actually missing from your emails or if it's not valid? In that case could you share it?
- Does this happen on any notification email from Mattermost or just some?

**Comment by dragonpil** [comment]
Hi @streamer45, 
so since around 2-3 weeks all emails gooing to google have this issue. So I see single messages & grouped notifications. As we don't allow active registering I can't confirm if it is also for this mails. 

When I have a look to the message in deed there is no Message-ID header field. A Message-ID header field could look like this: Message-ID: <cmu-lmtpd-2176282-1657021482-3@mb07.mail.vrmd.de> 
If no custom Message-ID header field is set by the sender (Mattermost in this case) the receiver could and will override it. Google is not doing this but block such mails since a short time.

**Comment by streamer45** [comment]
Thanks @dragonpil , looks like this was a [known issue](https://mattermost.atlassian.net/browse/MM-36872) which has been recently addressed in https://github.com/mattermost/mattermost-server/pull/18232

**Comment by dragonpil** [comment]
@streamer45  that will solve the issue. Sorry didn't saw that there is already an  merged PR for that. then I'm looking forward to the next release with the fix. Many, many thanks for you really good work.

**Comment by dragonpil** [comment]
So the regular notification error is gone with 7.2.0 here I don't get the MTA any more. 
I still get the MTA for google addresses  

- invitation to a team by email-address
- Welcome Email  after invitation 
- Password reset mails

Can we reopen this one or should I create a new one?
Robert
