### ISSUE TITLE
Admins can edit any message

### ISSUE THREAD

**Issue by M1dgard** [mattermost/mattermost-server#9307]
Original title: Anyone can edit or delete any message

#### Summary
Since I upgraded from 5.1 to 5.2, ~~anyone~~ *admins* can edit and delete any message, and as far as I can see it's not a configuration option. Still present in 5.2.1.

#### Steps to reproduce
1. Have someone send you a message.
2. *As an admin,* edit ~~or delete~~ it, like you would your own.

#### Expected behavior
There's a configuration option to turn this off.

#### Observed behavior (that appears unintentional) 
There's no way to turn this off.

~~PS: please DO include an option to keep this behaviour, the users of my instance and I love it! :smile:~~

**Comment by amyblais** [comment]
Hi @M1dgard, thank you for reaching out.

Is your team using [Advanced Permissions](https://docs.mattermost.com/deployment/advanced-permissions.html)?

If yes, there are options to allow anyone to edit/delete other's posts if enabled: https://docs.mattermost.com/deployment/advanced-permissions.html#system-scheme-e10.

I just tested this and I'm not able to reproduce this when the options to edit and delete others' posts are disabled, but I am able to reproduce this if those options are enabled.

**Comment by M1dgard** [comment]
Hi @amyblais, I have never heard of Advanced Permissions. I'm using the Team Edition, and Advanced Permissions is an Enterprise-only feature, right?

More info: I'm the system administrator for my instance, but this was reported to me by a regular user a few days after upgrading from 5.1.0 to 5.2.0. In DMs, editing doesn't seem to be possible, not even for me as SysAdmin: the option in the menu is visible, but when trying to save, a candybar "You do not have the appropriate permissions" appears.

I enabled debug logging and edited someone's message. These are the log messages that appear when I edit someone else's message:
```
{"level":"debug","ts":1535185028.6276839,"caller":"web/handlers.go:50","msg":"POST - /api/v4/channels/members/me/view"}
{"level":"debug","ts":1535185029.4745915,"caller":"web/handlers.go:50","msg":"PUT - /api/v4/posts/ac1zuo3uztngim79ijpbptu5uy/patch"}
{"level":"debug","ts":1535185029.8926384,"caller":"web/handlers.go:50","msg":"POST - /api/v4/channels/members/me/view"}
{"level":"debug","ts":1535185030.3992004,"caller":"web/handlers.go:50","msg":"POST - /api/v4/channels/members/me/view"}
{"level":"debug","ts":1535185030.6529145,"caller":"web/handlers.go:50","msg":"POST - /api/v4/users/status/ids"}
```

The startup log looks like this:
```
------------------------------------ ERROR ------------------------------------------------
The platform binary has been deprecated, please switch to using the new mattermost binary.
The platform binary will be removed in a future version.
-------------------------------------------------------------------------------------------
	
{"level":"info","ts":1535185060.554485,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/opt/mattermost/mattermost-5.2.1-team/i18n/en.json'"}
{"level":"info","ts":1535185060.5545392,"caller":"app/app.go:195","msg":"Server is initializing..."}
{"level":"info","ts":1535185060.5578191,"caller":"sqlstore/supplier.go:200","msg":"Pinging SQL master database"}
{"level":"error","ts":1535185060.5936282,"caller":"commands/server.go:74","msg":"The platform binary has been deprecated, please switch to using the mattermost binary."}
{"level":"info","ts":1535185060.593672,"caller":"commands/server.go:81","msg":"Current version is 5.2.0 (5.2.1/Thu Aug 23 17:03:54 UTC 2018/d2945cdd77bdf1ee03367a0d45624094fb936c19/none)"}
{"level":"info","ts":1535185060.5936844,"caller":"commands/server.go:82","msg":"Enterprise Enabled: false"}
{"level":"info","ts":1535185060.5936947,"caller":"commands/server.go:83","msg":"Current working directory is /opt/mattermost/mattermost-5.2.1-team"}
{"level":"info","ts":1535185060.5937805,"caller":"commands/server.go:84","msg":"Loaded config file from /etc/mattermost/mattermost.conf.json"}
{"level":"info","ts":1535185060.5939884,"caller":"utils/file_backend_local.go:32","msg":"Able to write files to local storage."}
{"level":"info","ts":1535185060.5948434,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"error","ts":1535185060.5948958,"caller":"app/plugin.go:108","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: permission denied"}
{"level":"info","ts":1535185060.594993,"caller":"app/server.go:88","msg":"Starting Server..."}
{"level":"info","ts":1535185060.5951061,"caller":"app/server.go:148","msg":"Server is listening on [::]:░░░░"}
{"level":"info","ts":1535185060.6070898,"caller":"app/web_hub.go:75","msg":"Starting 16 websocket hubs"}
{"level":"info","ts":1535185060.624317,"caller":"sqlstore/post_store.go:1261","msg":"Post.Message supports at most 4000 characters (4000 bytes)"}
{"level":"info","ts":1535185060.6248608,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"error","ts":1535185060.6249008,"caller":"app/plugin.go:108","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: permission denied"}
{"level":"info","ts":1535185060.6488416,"caller":"app/plugin.go:100","msg":"Starting up plugins"}
{"level":"error","ts":1535185060.6488822,"caller":"app/plugin.go:108","msg":"Failed to start up plugins","error":"mkdir ./client/plugins: permission denied"}
{"level":"info","ts":1535185060.6961296,"caller":"jobs/workers.go:62","msg":"Starting workers"}
{"level":"info","ts":1535185060.6962783,"caller":"jobs/schedulers.go:68","msg":"Starting schedulers."}
{"level":"error","ts":1535185063.4074552,"caller":"web/context.go:60","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins/webapp","request_id":"9m55optqmbfqmxuwq6m1s8eadr","ip_addr":"141.135.215.42","user_id":"b18thxzubtf59no83dsjfh6gcc","method":"GET","err_where":"GetActivePluginManifests","http_code":501,"err_details":""}
{"level":"error","ts":1535185063.554108,"caller":"web/context.go:60","msg":"Plugins have been disabled. Please check your logs for details.","path":"/api/v4/plugins/webapp","request_id":"1fxx7ybn37r6xc6tkgqrjaasse","ip_addr":"178.116.178.2","user_id":"e1pocwwq6tru5rajqcxrneypzw","method":"GET","err_where":"GetActivePluginManifests","http_code":501,"err_details":""}
```
(The plugins directory not being writeable is intentional.)

PS: I have since modified my service scriptto use `mattermost` instead of `platform`.

**Comment by amyblais** [comment]
Hi @M1dgard,

Thank you for the additional information - also:

1. What device / browser / OS are you seeing this on? 
2. Does this happen on public / private channels / teams? 
3. Is the user who reported this a Channel or Team Admin?

**Comment by amyblais** [comment]
I'm not able to reproduce this on a Team Edition test server, so I'll ask the team to take a look at the logs you shared in case there is some indication on the cause of the issue.

**Comment by M1dgard** [comment]
Sure, I've sent you an invite link via DM on pre-release.mattermost.com.

**Comment by M1dgard** [comment]
I did some more troubleshooting. Apparently you can only edit messages if you're System Admin or Team Admin (and only in the correct team).

Is it intended behaviour that admins can edit messages? It was definitely not possible in MM <5.0.0-team, and I think it was not possible in MM <5.2.0-team.

**Comment by amyblais** [comment]
Hi @M1dgard! I created a Jira ticket for this since I was able to reproduce the issue. I tagged it as "internal" since it looks like a confidential bug, so I can't link it here. I'll be giving updates on its progress here. Thanks for your patience and all the help you provided!

**Comment by amyblais** [comment]
Update: the Jira ticket I opened is not confidential but was closed as this other Jira ticket was already open that one of our devs is investigating: https://mattermost.atlassian.net/browse/MM-11707.

I think the devs are looking at adding a Team Edition config setting for this, but we'll have more details on this later.

**Comment by amyblais** [comment]
The Jira ticket linked above has been resolved and tested internally. The fix will be available in v5.4 release.

**Comment by bbodenmiller** [comment]
@amyblais there is still a bug here. Users who upgraded from 5.1 to 5.2 to 5.3 to 5.4 have this option (https://mattermost.atlassian.net/browse/MM-11707) set to True when before setting was added it was False. One of the installations set the flag to True and this should at least be noted in https://docs.mattermost.com/administration/important-upgrade-notes.html. Docs PR at https://github.com/mattermost/docs/pull/2505.

**Comment by almaceleste** [comment]
In 2025, in version 10.6.1, it is still not possible to disable editing of other people's messages for system administrators.

**Comment by carolyna** [comment]
Even in version 9.11.8 this option is set to true and cannot be disabled for sys admins.

**Comment by Squiddim** [comment]
In v10.8.0 its still not possible to disable editing others Posts for sysadmins
