### ISSUE TITLE
Remove hard black outline on scrollbar in Firefox/Win10

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9406]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12151)

#### Summary
Remove hard black outline on scrollbar in Firefox/Win10

#### Steps to reproduce
Open Mattermost in Firefox/Win10 and type enough messages into Town Square to trigger a scroll bar to the right of the center channel 

#### Observed behavior
Scroll bar in IE has heavy black outline 

![image](https://cloud.githubusercontent.com/assets/177788/21358832/df0be4b6-c68e-11e6-9081-e74c5e85430a.png)

#### Expected behavior
No heavy black outline, use outline color from user's theme. 

#### Possible fixes
Update existing scrollbar with `react-custom-scrollbars`.  

##### Note

There's a plug-in that's used to render the scrollbar in Chrome/Win10 that doesn't work in Firefox, so we just need to style the default scrollbar.

**Comment by eunicode** [comment]
I'd like to take on this issue.

**Comment by amyblais** [comment]
Thank you @eunicode!

**Comment by hanzei** [comment]
Hey @eunicode,

Can we help you with any questions?

**Comment by eunicode** [comment]
Hi @hanzei, thanks for checking in. I deeply apologize for not updating on my status sooner. I have been having problems setting up my development environment. However, I would love to try tackling this again, and would really appreciate one more week to work on this. If more time cannot be spared, I completely understand.

**Comment by hanzei** [comment]
Hey @eunicode,
Did you follow the steps on https://developers.mattermost.com/contribute/webapp/developer-setup/ already? You can also join [our Community Server](http://community.mattermost.com/) and ask for help there. It easier to solve setup problem in a chat room.

We are not in a hurry. I wanted to check if you are still working on this. Take the time you need! And let us know (here or on the community server) if you need help.

**Comment by eunicode** [comment]
@hanzei Yes, I've done both, but I will try again and experiment with new configurations (I think my problems might stem from using MinTTY), and then ask for help in the community server. Thank you so much for being so understanding.

**Comment by andreicristianpetcu** [comment]
I man aged to make the scrollbars pretty in Firefox with this CSS.

```css
.more-modal__list div, .modal-body, body div { 
  scrollbar-color: #aaaaaa rgba(255, 255, 255, .0);
  scrollbar-width: thin;
}
```
![before](https://user-images.githubusercontent.com/922368/52565327-2c0dcd80-2e0f-11e9-932c-c13d1d133aa3.png)
![after](https://user-images.githubusercontent.com/922368/52565335-2f08be00-2e0f-11e9-9390-f4606175e977.png)

GNU/Linux, Firefox Nightly v67 (should work in stable also)

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by jkl5616** [comment]
I'd like to take this!

**Comment by andreicristianpetcu** [comment]
I don't use MM anymore but this should fix it https://addons.mozilla.org/en-US/firefox/addon/dark-scroll-for-tweetdeck/

**Comment by hanzei** [comment]
@jasonblais Could you check if this issue still exists, as you are the reporter of the original ticket?

**Comment by jasonblais** [comment]
@hanzei Thanks for checking, still reproduces.

@jkl5616 Thanks for your interest & thanks @andreicristianpetcu for the tip!

**Comment by jkl5616** [comment]
@hanzei I think I can just apply "Center Text Channel" color as same as in Chrome to FireFox/Win10 and IE11/Win10 to match with themes. As IE11 does not supports alpha background, just calculating the background color and apply the color as face and track is a best way. Will this approach enough to solve the issue?

**Comment by hanzei** [comment]
The support of IE11 will be dropped with Mattermost `v5.16`. You don't have to worry about this special case.

**Comment by jasonblais** [comment]
@jkl5616 Agree with Hanzei, I've updated the ticket to specify Firefox. We can focus on resolving this ticket for Firefox only.

Thanks for your help on this ticket!

**Comment by hanzei** [comment]
Hey @jkl5616,

How is your work on this ticket going? Do you have further questions?

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by mujz** [comment]
Just some notes for whoever picks this ticket up, it seems to me that the work required to resolve this issue is to add [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars) CSS property to [_scrollbar.scss](https://github.com/mattermost/mattermost-webapp/blob/master/sass/components/_scrollbar.scss).

**Comment by mujz** [comment]
@esethna @jasonblais @hanzei can one of you folks confirm if this is still happening? We tried to reproduce this using the steps you defined in above and in [the JIRA ticket](https://mattermost.atlassian.net/browse/MM-12151), but weren't able to get the problem to appear. If you can reproduce it, would you mind specifying the version of Firefox you used to reproduce the error?

Thanks!

**Comment by hanzei** [comment]
I can't repo this on Firefox 70.0.1

![Screenshot from 2019-11-25 14-49-02](https://user-images.githubusercontent.com/16541325/69545779-bedcba80-0f92-11ea-84e4-e8c0bd93b93b.png)

**Comment by jasonblais** [comment]
Thanks @mujz and @hanzei. I don't have access to a Windows machine right now, so I'll close this issue and ask QA to help test the Jira ticket. We can reopen if we're able to reproduce it.

Thanks for looking into it!
